### PR TITLE
Add Pluto SDR support.

### PR DESCRIPTION
**Pull request by gsqrd**
Add support for Pluto SDR via libiio. Support is disabled by default, can be enabled with -DENABLE_SDR_PLUTO=ON and requires libiio. 
Tested successfully with GOES GVAR at 3Msps over Ethernet.

### CODE REVIEW

**Comment by AlexandreRouma** [comment]
You also need to use libad9361 to properly configure the transceiver's filters according to the samplerate. See AD's example code for the pluto.

**Comment by gsqrd** [comment]
I didn't think you need to set filters if you're not doing <2.1Msps?

**Comment by Aang23** [comment]
Hm. I really thought I had replied there long ago...

First of all, thanks a lot for your PR! Overall it looks pretty good, would mostly have to update things a bit.
Though... I agree with @AlexandreRouma, setting filters properly (or having support for that) is required. While most usecases will probably be at higher samplerates, not all of them (such as LRPT for example).

I should be able to test everything with the hardware & finish things up soon enough though.

**Comment by Aang23** [comment]
Added.

**Pull request closed without merging**
