### PR TITLE
Add CRC check to GVAR headers

### PR DESCRIPTION
**Pull request by errolt**
I have copied the CRC table and code from electro.
The code tries to find the first successful CRC header, else switches to most_common block_id.
I have expanded the header struct to decoded the header date/time. For future use.

### CODE REVIEW

**Comment by Aang23** [comment]
Thanks! Will test and probably merge shortly.

**Comment by errolt** [comment]
Thanks. 
After a lot of struggling I found that all the int16 variables in the block header, including the crc, are all byte-swapped. In my other PR I added classes do "unswap" those variables, in case the become useful.

**Comment by Aang23** [comment]
It's common indeed, the downlink uses big-endian. Usually I parse them in a way that avoids the issue though. (I still didn't check your code in details though!)

I'd guess a more generic endianess swap class could come in handy, for what can be described in packed structs. (though when it's for reading very little, may be overkill)

**Comment by errolt** [comment]
I did add endian swapping classes in my other commit, for 16 bit, 32 bit. And bytes-wapping/decoding for floats, but this code is nasty.
VS code refuses to parse those classes in the struct when debugging/watching a variable. I don't know if I did something wrong. I have checked the decoded data by setting, for example, a float variables equal to Block0header.SUBLA and Block0header.SUBLO, which is the satellite's latitude and longitude and got 0 & 61.499939

**Comment by Aang23** [comment]
Just to be sure : Do I need to merge both this PR and the other one?

I checked both, looks good to me otherwise.

**Comment by errolt** [comment]
This seems to be covered by the other PR. I'll close this one.

**Pull request closed without merging**
