### PR TITLE
Add WAV output support to satdump-recorder

### PR DESCRIPTION
**Pull request by Blobtoe**
I added 16-bit WAV output format to satdump-recorder, and slightly changed the input parameter syntax. Also added a few code comments.

### CODE REVIEW

**Comment by Aang23** [comment]
@Blobtoe thanks, but unfortunately things changed massively. If you still want to do it, I'd gladly merge it once redone against the latest code.

**Comment by Blobtoe** [comment]
Sure, I'll look at the new code and see if I can implement it again. Not too experienced with c++ though, so we'll see.

**Comment by Aang23** [comment]
Just tested - works and changes look mostly good to me. Is it ready? If so, will likely merge tomorrow as I got to sleep now!

**Comment by Blobtoe** [comment]
Yeah, should be good to go. I might update the readme aswell.

**Comment by Aang23** [comment]
Ah one thing actually : when you write the header, it would be better to use fixed-size variable types such as uint16_t, uint32_t and so on as that will guarantee things will not break on a platform with a different implementation of int for example. Unsigned are also preferred as values in the wav header specificarion are unsigned.

**Comment by Aang23** [comment]
Ah and in the recorder GUI as you added WAV, int values for ZIQ should all incremented to +1. Some code below may also need that - but I can always check when merging if necessary.

**Comment by Blobtoe** [comment]
Yep good catch

**Comment by Aang23** [comment]
Merged! I just changed the variables to the right byte sizes.

**Comment by Aang23** [comment]
One thing that may be handy as well would be support 8-bits WAV, may be useful for some users. I'll keep that in mind.

**Pull request merged**
