### PR TITLE
Added experimental MSU-MR Natural Color composite

### PR DESCRIPTION
**Pull request by RAD750**
I got a bit tired of the toothpaste color in the MSU-MR clouds, so I tried adding a (very) experimental natural color CSWIR+NIR composite. It looks right on vegetated land, however the Sahara looks like it's covered in some sort of mold :joy: , so clearly some improvements are still needed. Feel free to reject if it seems too experimental for inclusion!

msu_mr_composite

### CODE REVIEW

**Comment by ZbychuButItWasTaken** [comment]
For now I wouldn't merge it, I'd rather wait for it to be in the finished state.. You can try experimenting with desaturating cyan on these clouds (so basically when ch3 is lower than the other channels). That should work pretty alright

**Comment by Aang23** [comment]
I think we'd better keep this PR open for discussion perhaps! I'm also quite interested.
But indeed, maybe a bit too "experimental" to merge as-is.

**Comment by RAD750** [comment]
Thanks for the insight guys, that's why I made the PR! 
After a very successful Atlantic passage of MN2-2 I started experimenting again and after the insight of @ZbychuButItWasTaken I tried simply adding to the red channel 0.3*ch3 (formula: `(0.5*max(ch4,min(ch2,ch1)) + 0.5*ch2)+0.3*ch3, ch2, ch1`), this seems to produce acceptable quality images without making the Sahara desert look like milk left too long in a fridge. 
natural_color

The only issue I still see, is that the sea/ocean has a red tint on it, probably because the red channel is too saturated. But I managed to fix that too, new formula: `((0.5*max(ch4,min(ch2,ch1)) + 0.5*ch2)+0.3*ch3)^1.2, ch2, ch1`
And the result:
natural_color_fix

Let me know what you think!

**Comment by RAD750** [comment]
Also, it would appear that white balancing the image fixes the issue without adding any exponent
(formula: `((0.5*max(ch4,min(ch2,ch1)) + 0.5*ch2)+0.3*ch3), ch2, ch1`)
Result:
msu_mr_4_Equalized

**Comment by Aang23** [comment]
That does look pretty decent! Would probably be a bit better with a bit more contrast, but that'd be getting difficult to do with just that math. (Or perhaps square-root enhancement but not quite sure)

Looks to me, thoughts @ZbychuButItWasTaken?

**Comment by RAD750** [comment]
Slightly reduced red
`((0.5*max(ch4,min(ch2,ch1)) + 0.5*ch2)+0.3*ch3)*0.85, ch2, ch1`

If you're satisfied I'll push again
White balancing makes it looks much better still, so I will enable the option. It would appear however that the image is not saved with white balancing enabled from the Viewer (?)

msu

**Comment by ZbychuButItWasTaken** [comment]
Yep looks good, you can push the changes and I will test it out and some more data to make sure it's good on other data too

**Comment by Aang23** [comment]
Looks totally fine for me! And relying on white balance is fine!

**Pull request merged**
