### PR TITLE
Basic HRIT platform for FengYun-4

### PR DESCRIPTION
**Pull request by Foxiks**

### CODE REVIEW

**Comment by Aang23** [comment]
It is not QPSK but also DVB-S2. Are you able to provide a baseband perhaps? If you are, I can decode it down to CADUs... And then if you can harvest even more data, there sometimes is some unencrypted files to be decoded.

**Comment by Foxiks** [comment]
Yes, I have two BB records, but they have ~3 dB SNR. This will be enough?

**Comment by Aang23** [comment]
Well, a bit borderline but one way to find out!

**Comment by Foxiks** [comment]
Excellent! Give me about 10 minutes to upload this!

**Comment by Aang23** [comment]
The "hard limit" as per the standard for the FEC it uses is ~2db.

**Comment by Aang23** [comment]
I was wrong... It's not QPSK 3/5 but 5/6, so less FEC. I am still able to lock though, but the resulting frames are too noisy to extract CADUs from the TS. ~2db more would be required, which maybe you could get with a linear feed if you were not using that.

Screenshot from 2022-10-28 15-02-49
Screenshot from 2022-10-28 15-06-33
Screenshot from 2022-10-28 15-07-55

The pipeline used was :
```
    "fengyun4_hrit": {
        "name": "FengYun-4 HRIT",
        "live": true,
        "live_cfg": [
            [
                1,
                0
            ],
            [
                2,
                0
            ]
        ],
        "frequencies": [
            [
                "HRIT",
                1679e6
            ]
        ],
        "work": {
            "baseband": {},
            "bbframe": {
                "dvbs2_demod": {
                    "symbolrate": 1e6,
                    "rrc_alpha": 0.25,
                    "pll_bw": 0.001,
                    "clock_alpha": 2.5e-3,
                    "modcod": 9
                }
            },
            "cadu": {
                "s2_udp_cadu_extractor": {
                    "bb_size": 53840,
                    "pid": 3002
                }
            }
        }
    }
```

**Comment by Foxiks** [comment]
Wow! It is perfectly! I'll try to do it with a linear feed, but a bit later...

**Comment by Aang23** [comment]
Yes... Pretty impressive it locks at such low SNRs, but the DVB-S2 frames can clearly be seen.
It'd be nice if you do sometime! The further layers to get imagery out (well, what is not DES-encrypted) are pretty straightforward, but getting the data has been the primary challenge.

**Comment by Foxiks** [comment]
Yes, I will definitely try this in the future! Anyway, great job!

**Comment by Foxiks** [comment]
Hm. I have a problem that DVB-S demodulator and decoder does not work in win. This gives no output and when you try to stop the demodulator it crashes the program.

**Comment by Aang23** [comment]
Oh? I will give that a go a bit later in my VM.

**Comment by Aang23** [comment]
Also, I will close this PR (as I pushed the demodulator) and instead open an issue about FengYun-4.

**Comment by Foxiks** [comment]
Okay!

**Pull request closed without merging**
